# CESGA: 
# file(GLOB REAL_QPUS_SCRIPTS "${CMAKE_CURRENT_SOURCE_DIR}/*.py")
# install(FILES ${REAL_QPUS_SCRIPTS} DESTINATION cunqa/real_qpus)

#Lusitania
file(GLOB REAL_QPUS_SCRIPTS "${CMAKE_CURRENT_SOURCE_DIR}/*.py")

# USAR LA VARIABLE DEL PADRE PARA CAER EN SITE-PACKAGES
install(FILES ${REAL_QPUS_SCRIPTS} DESTINATION "${CUNQA_PYTHON_INSTALL_DIR}/real_qpus")