name: tests

on: 
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Create stub cunqa/qclient.py (empty QClient)
        shell: bash
        run: |
          cat > cunqa/qclient.py <<'PY'
          class QClient:
              def connect(self, a):
                pass
          class FutureWrapper:
              pass

          def write_on_file(a, b, c):
            pass
          def qasm2_to_json(a):
            pass
          def json_to_qasm2(a):
            pass
          PY
      - name: Create stub cunqa/counts_and_probs.py (empty counts_and_probs)
        shell: bash
        run: |
          cat > cunqa/counts_and_probs.py <<'PY'
          def marginalize_counts(counts, region_sizes, check_lenght = False):
            pass
          def recombine_probs(probs, per_qubit, partial, num_qubits):
            pass
          def counts_to_probs(counts, per_qubit = False, partial = None):
            pass
          PY
      - name: Copy constants.py.in into constants.py
        run:
          cp cunqa/constants.py.in cunqa/constants.py
      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install qiskit==1.2.4 pytest pyzmq==25.* qiskit-aer psutil

      - name: Run tests
        run: |
          pytest -q tests/